version: "3.9"

services:
  app:
    build: .
    container_name: balancee-app-prod
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ENVIRONMENT=prod
      - FLYWAY_ENABLE=${FLYWAY_ENABLE}
    depends_on:
      - database
    command: ./wait-for-it.sh database:${POSTGRES_PORT} -t 30 -- java -jar /app/balancee.jar

  database:
    image: postgres:15
    container_name: balancee-db
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
