services:
  app:
    build: .
    container_name: balancee-app-dev
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - ENVIRONMENT=dev
      - SPRING_DATASOURCE_URL=${DATABASE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./data:/app/data