spring:
  # Datasource Configuration
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    driver: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  # Hibernate JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  # Flyway Database Migration Configuration
  flyway:
    enabled: ${FLYWAY_ENABLE}
    locations: classpath:db/migration